package com.hj.dao;

import com.hj.entity.HjStoreProduct;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface HjStoreProductMapper {
    @Delete({
        "delete from hj_store_product",
        "where product_id = #{productId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer productId);

    @Insert({
        "insert into hj_store_product (product_id, mer_id, ",
        "store_name, store_info, ",
        "keyword, bar_code, ",
        "brand_id, is_show, ",
        "status, is_del, mer_status, ",
        "cate_id, unit_name, ",
        "sort, rank, sales, ",
        "price, cost, ot_price, ",
        "stock, is_hot, is_benefit, ",
        "is_best, is_new, is_good, ",
        "product_type, ficti, ",
        "browse, code_path, ",
        "video_link, temp_id, ",
        "spec_type, extension_type, ",
        "refusal, rate, reply_count, ",
        "give_coupon_ids, is_gift_bag, ",
        "create_time, care_count, ",
        "is_used, old_product_id, ",
        "image, slider_image, ",
        "guarantee_template_id, once_count, ",
        "integral_rate, integral_total, ",
        "integral_price_total, labels, ",
        "delivery_way, delivery_free, ",
        "type, extend, block_id)",
        "values (#{productId,jdbcType=INTEGER}, #{merId,jdbcType=INTEGER}, ",
        "#{storeName,jdbcType=VARCHAR}, #{storeInfo,jdbcType=VARCHAR}, ",
        "#{keyword,jdbcType=VARCHAR}, #{barCode,jdbcType=VARCHAR}, ",
        "#{brandId,jdbcType=INTEGER}, #{isShow,jdbcType=TINYINT}, ",
        "#{status,jdbcType=BIT}, #{isDel,jdbcType=TINYINT}, #{merStatus,jdbcType=BIT}, ",
        "#{cateId,jdbcType=INTEGER}, #{unitName,jdbcType=VARCHAR}, ",
        "#{sort,jdbcType=SMALLINT}, #{rank,jdbcType=SMALLINT}, #{sales,jdbcType=INTEGER}, ",
        "#{price,jdbcType=DECIMAL}, #{cost,jdbcType=DECIMAL}, #{otPrice,jdbcType=DECIMAL}, ",
        "#{stock,jdbcType=INTEGER}, #{isHot,jdbcType=TINYINT}, #{isBenefit,jdbcType=TINYINT}, ",
        "#{isBest,jdbcType=TINYINT}, #{isNew,jdbcType=TINYINT}, #{isGood,jdbcType=BIT}, ",
        "#{productType,jdbcType=TINYINT}, #{ficti,jdbcType=INTEGER}, ",
        "#{browse,jdbcType=INTEGER}, #{codePath,jdbcType=VARCHAR}, ",
        "#{videoLink,jdbcType=VARCHAR}, #{tempId,jdbcType=INTEGER}, ",
        "#{specType,jdbcType=BIT}, #{extensionType,jdbcType=BIT}, ",
        "#{refusal,jdbcType=VARCHAR}, #{rate,jdbcType=DECIMAL}, #{replyCount,jdbcType=INTEGER}, ",
        "#{giveCouponIds,jdbcType=VARCHAR}, #{isGiftBag,jdbcType=BIT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{careCount,jdbcType=INTEGER}, ",
        "#{isUsed,jdbcType=INTEGER}, #{oldProductId,jdbcType=INTEGER}, ",
        "#{image,jdbcType=VARCHAR}, #{sliderImage,jdbcType=VARCHAR}, ",
        "#{guaranteeTemplateId,jdbcType=INTEGER}, #{onceCount,jdbcType=INTEGER}, ",
        "#{integralRate,jdbcType=INTEGER}, #{integralTotal,jdbcType=INTEGER}, ",
        "#{integralPriceTotal,jdbcType=DECIMAL}, #{labels,jdbcType=VARCHAR}, ",
        "#{deliveryWay,jdbcType=VARCHAR}, #{deliveryFree,jdbcType=INTEGER}, ",
        "#{type,jdbcType=TINYINT}, #{extend,jdbcType=VARCHAR}, #{blockId,jdbcType=INTEGER})"
    })
    int insert(HjStoreProduct record);

    @InsertProvider(type=HjStoreProductSqlProvider.class, method="insertSelective")
    int insertSelective(HjStoreProduct record);

    @Select({
        "select",
        "product_id, mer_id, store_name, store_info, keyword, bar_code, brand_id, is_show, ",
        "status, is_del, mer_status, cate_id, unit_name, sort, rank, sales, price, cost, ",
        "ot_price, stock, is_hot, is_benefit, is_best, is_new, is_good, product_type, ",
        "ficti, browse, code_path, video_link, temp_id, spec_type, extension_type, refusal, ",
        "rate, reply_count, give_coupon_ids, is_gift_bag, create_time, care_count, is_used, ",
        "old_product_id, image, slider_image, guarantee_template_id, once_count, integral_rate, ",
        "integral_total, integral_price_total, labels, delivery_way, delivery_free, type, ",
        "extend, block_id",
        "from hj_store_product",
        "where product_id = #{productId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="product_id", property="productId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="mer_id", property="merId", jdbcType=JdbcType.INTEGER),
        @Result(column="store_name", property="storeName", jdbcType=JdbcType.VARCHAR),
        @Result(column="store_info", property="storeInfo", jdbcType=JdbcType.VARCHAR),
        @Result(column="keyword", property="keyword", jdbcType=JdbcType.VARCHAR),
        @Result(column="bar_code", property="barCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="brand_id", property="brandId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_show", property="isShow", jdbcType=JdbcType.TINYINT),
        @Result(column="status", property="status", jdbcType=JdbcType.BIT),
        @Result(column="is_del", property="isDel", jdbcType=JdbcType.TINYINT),
        @Result(column="mer_status", property="merStatus", jdbcType=JdbcType.BIT),
        @Result(column="cate_id", property="cateId", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_name", property="unitName", jdbcType=JdbcType.VARCHAR),
        @Result(column="sort", property="sort", jdbcType=JdbcType.SMALLINT),
        @Result(column="rank", property="rank", jdbcType=JdbcType.SMALLINT),
        @Result(column="sales", property="sales", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="cost", property="cost", jdbcType=JdbcType.DECIMAL),
        @Result(column="ot_price", property="otPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="stock", property="stock", jdbcType=JdbcType.INTEGER),
        @Result(column="is_hot", property="isHot", jdbcType=JdbcType.TINYINT),
        @Result(column="is_benefit", property="isBenefit", jdbcType=JdbcType.TINYINT),
        @Result(column="is_best", property="isBest", jdbcType=JdbcType.TINYINT),
        @Result(column="is_new", property="isNew", jdbcType=JdbcType.TINYINT),
        @Result(column="is_good", property="isGood", jdbcType=JdbcType.BIT),
        @Result(column="product_type", property="productType", jdbcType=JdbcType.TINYINT),
        @Result(column="ficti", property="ficti", jdbcType=JdbcType.INTEGER),
        @Result(column="browse", property="browse", jdbcType=JdbcType.INTEGER),
        @Result(column="code_path", property="codePath", jdbcType=JdbcType.VARCHAR),
        @Result(column="video_link", property="videoLink", jdbcType=JdbcType.VARCHAR),
        @Result(column="temp_id", property="tempId", jdbcType=JdbcType.INTEGER),
        @Result(column="spec_type", property="specType", jdbcType=JdbcType.BIT),
        @Result(column="extension_type", property="extensionType", jdbcType=JdbcType.BIT),
        @Result(column="refusal", property="refusal", jdbcType=JdbcType.VARCHAR),
        @Result(column="rate", property="rate", jdbcType=JdbcType.DECIMAL),
        @Result(column="reply_count", property="replyCount", jdbcType=JdbcType.INTEGER),
        @Result(column="give_coupon_ids", property="giveCouponIds", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_gift_bag", property="isGiftBag", jdbcType=JdbcType.BIT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="care_count", property="careCount", jdbcType=JdbcType.INTEGER),
        @Result(column="is_used", property="isUsed", jdbcType=JdbcType.INTEGER),
        @Result(column="old_product_id", property="oldProductId", jdbcType=JdbcType.INTEGER),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR),
        @Result(column="slider_image", property="sliderImage", jdbcType=JdbcType.VARCHAR),
        @Result(column="guarantee_template_id", property="guaranteeTemplateId", jdbcType=JdbcType.INTEGER),
        @Result(column="once_count", property="onceCount", jdbcType=JdbcType.INTEGER),
        @Result(column="integral_rate", property="integralRate", jdbcType=JdbcType.INTEGER),
        @Result(column="integral_total", property="integralTotal", jdbcType=JdbcType.INTEGER),
        @Result(column="integral_price_total", property="integralPriceTotal", jdbcType=JdbcType.DECIMAL),
        @Result(column="labels", property="labels", jdbcType=JdbcType.VARCHAR),
        @Result(column="delivery_way", property="deliveryWay", jdbcType=JdbcType.VARCHAR),
        @Result(column="delivery_free", property="deliveryFree", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.TINYINT),
        @Result(column="extend", property="extend", jdbcType=JdbcType.VARCHAR),
        @Result(column="block_id", property="blockId", jdbcType=JdbcType.INTEGER)
    })
    HjStoreProduct selectByPrimaryKey(Integer productId);

    @UpdateProvider(type=HjStoreProductSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(HjStoreProduct record);

    @Update({
        "update hj_store_product",
        "set mer_id = #{merId,jdbcType=INTEGER},",
          "store_name = #{storeName,jdbcType=VARCHAR},",
          "store_info = #{storeInfo,jdbcType=VARCHAR},",
          "keyword = #{keyword,jdbcType=VARCHAR},",
          "bar_code = #{barCode,jdbcType=VARCHAR},",
          "brand_id = #{brandId,jdbcType=INTEGER},",
          "is_show = #{isShow,jdbcType=TINYINT},",
          "status = #{status,jdbcType=BIT},",
          "is_del = #{isDel,jdbcType=TINYINT},",
          "mer_status = #{merStatus,jdbcType=BIT},",
          "cate_id = #{cateId,jdbcType=INTEGER},",
          "unit_name = #{unitName,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=SMALLINT},",
          "rank = #{rank,jdbcType=SMALLINT},",
          "sales = #{sales,jdbcType=INTEGER},",
          "price = #{price,jdbcType=DECIMAL},",
          "cost = #{cost,jdbcType=DECIMAL},",
          "ot_price = #{otPrice,jdbcType=DECIMAL},",
          "stock = #{stock,jdbcType=INTEGER},",
          "is_hot = #{isHot,jdbcType=TINYINT},",
          "is_benefit = #{isBenefit,jdbcType=TINYINT},",
          "is_best = #{isBest,jdbcType=TINYINT},",
          "is_new = #{isNew,jdbcType=TINYINT},",
          "is_good = #{isGood,jdbcType=BIT},",
          "product_type = #{productType,jdbcType=TINYINT},",
          "ficti = #{ficti,jdbcType=INTEGER},",
          "browse = #{browse,jdbcType=INTEGER},",
          "code_path = #{codePath,jdbcType=VARCHAR},",
          "video_link = #{videoLink,jdbcType=VARCHAR},",
          "temp_id = #{tempId,jdbcType=INTEGER},",
          "spec_type = #{specType,jdbcType=BIT},",
          "extension_type = #{extensionType,jdbcType=BIT},",
          "refusal = #{refusal,jdbcType=VARCHAR},",
          "rate = #{rate,jdbcType=DECIMAL},",
          "reply_count = #{replyCount,jdbcType=INTEGER},",
          "give_coupon_ids = #{giveCouponIds,jdbcType=VARCHAR},",
          "is_gift_bag = #{isGiftBag,jdbcType=BIT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "care_count = #{careCount,jdbcType=INTEGER},",
          "is_used = #{isUsed,jdbcType=INTEGER},",
          "old_product_id = #{oldProductId,jdbcType=INTEGER},",
          "image = #{image,jdbcType=VARCHAR},",
          "slider_image = #{sliderImage,jdbcType=VARCHAR},",
          "guarantee_template_id = #{guaranteeTemplateId,jdbcType=INTEGER},",
          "once_count = #{onceCount,jdbcType=INTEGER},",
          "integral_rate = #{integralRate,jdbcType=INTEGER},",
          "integral_total = #{integralTotal,jdbcType=INTEGER},",
          "integral_price_total = #{integralPriceTotal,jdbcType=DECIMAL},",
          "labels = #{labels,jdbcType=VARCHAR},",
          "delivery_way = #{deliveryWay,jdbcType=VARCHAR},",
          "delivery_free = #{deliveryFree,jdbcType=INTEGER},",
          "type = #{type,jdbcType=TINYINT},",
          "extend = #{extend,jdbcType=VARCHAR},",
          "block_id = #{blockId,jdbcType=INTEGER}",
        "where product_id = #{productId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(HjStoreProduct record);
}